replicaCount: 3
index: 1

config:
  configSecretName: tsm0-config

image:
  repository: <the name of the repository where tsm-node is stored>
  pullPolicy: IfNotPresent
  tag: "61.0.2"

sdkService:
  type: NodePort
  ports:
    - port: 8080
      name: sdk
      targetPort: 8080
    - port: 9000
      name: mpc
      targetPort: 9000

mpcService:
  enabled: false

ingress:
  enabled: false
