apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tsm-node.fullname" . }}
  labels:
    {{- include "tsm-node.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.config.configFile | nindent 4 }}