apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsm-node.fullname" . }}
  labels:
    {{- include "tsm-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sdkService.type }}
  ports:
  {{- range .Values.sdkService.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "tsm-node.selectorLabels" . | nindent 4 }}
