apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsm-audit-server.fullname" . }}
  labels:
    {{- include "tsm-audit-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tsm-audit-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tsm-audit-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tsm-audit-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.service.ports }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
              protocol: TCP
          {{- end }}
          {{- if .Values.env }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /ping
              port: query
          readinessProbe:
            httpGet:
              path: /ping
              port: query
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
          - name: config-volume
            mountPath: /config
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      - name: config-volume
        {{- if and .Values.config.configFile .Values.config.configSecretName }}
        {{- fail "config.configFile and config.configSecretName are mutually exclusive" }}
        {{- else if .Values.config.configFile }}
        configMap:
          name: {{ template "tsm-audit-server.fullname" . }}
        {{- else if .Values.config.configSecretName }}
        secret:
          secretName: {{ .Values.config.configSecretName }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
