apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsm-audit-server.fullname" . }}
  labels:
    {{- include "tsm-audit-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "tsm-audit-server.selectorLabels" . | nindent 4 }}
