
[Player]
	Index = 0
	PrivateKey = "MHcCAQEEIJZ2T0ESxG34wA77rhn+9KMOrkz296jeDUOenHsLmWO/oAoGCCqGSM49AwEHoUQDQgAE0AyIB0e0A00Z+ovqDQ5mjffEqVabU/eEOwOOrkElnSX1qPkgIn5eLIOC7OWQq6dgZnJLjElg6R4vR5a91aAE8w=="
	ExportWhiteList = ["*"]

[Players.0]
	Address = "tcp://tsm0-tsm-node:9000"
	PublicKey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0AyIB0e0A00Z+ovqDQ5mjffEqVabU/eEOwOOrkElnSX1qPkgIn5eLIOC7OWQq6dgZnJLjElg6R4vR5a91aAE8w=="

[Players.1]
	Address = "tcp://tsm1-tsm-node:9000"
	PublicKey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZsbGXaVTkx8iiXb7iDSBFs24xYdbe5jTRg57aU0F71BMxhlV46cKMsCDXARriCUBwApfCoAf/ByyJ7TpWRm4Rw=="

[Players.2]
	Address = "tcp://tsm2-tsm-node:9000"
	PublicKey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJZx6N1ARYmc/6DQBL/47yRL/dMvWi5UQRUiqA05pdjLAb3eXO6yPioocnZNxsQjCerxcMJ2LnvELmK5L6Ovsqw=="

[Database]
	DriverName = "postgres"
	DataSourceName = "postgres://db0user:db0password@db0:5432/db0?sslmode=disable"
	EncryptorMasterPassword = "db0masterPassword"

[MPCTCPServer]
	Port = 9000

[SDKServer]
	Port = 8080

[ManagementServer]
    Port = 14401
[ManagementServer.Metrics]
    Prometheus = true
[[ManagementServer.APIKeys]]
    APIKey = "R72Y5Qx3qCtC6yK8EgOIN5SYlibRmZ6CKnXZvgJtSeo=" # mgmtapikey0
    Permissions=["HEALTH", "TSMINFO", "METRICS" ]

[[Authentication.APIKeys]]
	APIKey = "IntV2sEZRwwd2F+UkDLC7zmFhwvpxAwb0eQKwdEnSZU=" # apikey0
	ApplicationID = "demoapp"

[[Authentication.APIKeys]]
    APIKey = "NaseBBHEzG7KqmdqTH/vJZeYeZ7UCtCfsHra6QK9DHo=" # apikey3
    ApplicationID = "app2"

[MultiInstance]
    Address = "{{ env `TSM_MULTIINSTANCE_ADDRESS` }}"
    CleanupInterval = "5m"
    CleanupProbability = 75

[DKLS19.Features]
    GenerateKey = true
    GeneratePresignatures = true
    Sign = true
    SignWithPresignature = true
    GenerateRecoveryData = true
    PublicKey = true
    ChainCode = true
    Reshare = true
    CopyKey = true
    ExportKeyShare = true
    ImportKeyShare = true
    ExportKey = true
    ImportKey = true
    BIP32GenerateSeed = true
    BIP32DeriveFromSeed = true
    BIP32DeriveFromKey = true
    BIP32ConvertKey = true
    BIP32ExportSeed = true
    BIP32ImportSeed = true
    BIP32Info = true

[SEPD19S.Features]
    GenerateKey = true
    GeneratePresignatures = true
    Sign = true
    SignWithPresignature = true
    GenerateRecoveryData = true
    PublicKey = true
    ChainCode = true
    Reshare = true
    CopyKey = true
    ExportKeyShare = true
    ImportKeyShare = true
    ExportKey = true
    ImportKey = true

[ADN06.Features]
    PublicKey = true
    SignPKCS1v15 = true
    SignPSS = true
    Decrypt = true
    ExportKey = true
    ImportKey = true

[MRZ15.AESFeatures]
    GenerateKey = true
    ExportKey = true
    ImportKey = true
    CTRKeyStream = true
    CBCEncrypt = true
    CBCDecrypt = true
    GCMEncrypt = true
    GCMDecrypt = true
    CMAC = true

[MRZ15.HMACFeatures]
    GenerateKey = true
    ExportKey = true
    ImportKey = true
    HMACSHA256 = true
    HMACSHA512 = true
